package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1



/**
 * Adminmessages generated by hbm2java
 */
public class Adminmessages  implements java.io.Serializable {


     private Integer messageId;
     private Users usersByMessageFrom;
     private Users usersByMessageTo;
     private String messageSubject;
     private String messageBody;

    public Adminmessages() {
    }

    public Adminmessages(Users usersByMessageFrom, Users usersByMessageTo, String messageSubject, String messageBody) {
       this.usersByMessageFrom = usersByMessageFrom;
       this.usersByMessageTo = usersByMessageTo;
       this.messageSubject = messageSubject;
       this.messageBody = messageBody;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public Users getUsersByMessageFrom() {
        return this.usersByMessageFrom;
    }
    
    public void setUsersByMessageFrom(Users usersByMessageFrom) {
        this.usersByMessageFrom = usersByMessageFrom;
    }
    public Users getUsersByMessageTo() {
        return this.usersByMessageTo;
    }
    
    public void setUsersByMessageTo(Users usersByMessageTo) {
        this.usersByMessageTo = usersByMessageTo;
    }
    public String getMessageSubject() {
        return this.messageSubject;
    }
    
    public void setMessageSubject(String messageSubject) {
        this.messageSubject = messageSubject;
    }
    public String getMessageBody() {
        return this.messageBody;
    }
    
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }




}


