package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BookingStatus generated by hbm2java
 */
public class BookingStatus  implements java.io.Serializable {


     private String bookingStatusCode;
     private String bookingStatusDescription;
     private Set bookings = new HashSet(0);

    public BookingStatus() {
    }

	
    public BookingStatus(String bookingStatusCode) {
        this.bookingStatusCode = bookingStatusCode;
    }
    public BookingStatus(String bookingStatusCode, String bookingStatusDescription, Set bookings) {
       this.bookingStatusCode = bookingStatusCode;
       this.bookingStatusDescription = bookingStatusDescription;
       this.bookings = bookings;
    }
   
    public String getBookingStatusCode() {
        return this.bookingStatusCode;
    }
    
    public void setBookingStatusCode(String bookingStatusCode) {
        this.bookingStatusCode = bookingStatusCode;
    }
    public String getBookingStatusDescription() {
        return this.bookingStatusDescription;
    }
    
    public void setBookingStatusDescription(String bookingStatusDescription) {
        this.bookingStatusDescription = bookingStatusDescription;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }




}


