package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BookingRoomUpdate generated by hbm2java
 */
public class BookingRoomUpdate  implements java.io.Serializable {


     private Integer bookingUpdateId;
     private Booking booking;
     private Rooms roomsByNewRoomId;
     private Rooms roomsByOldRoomId;
     private Date dateUpdated;

    public BookingRoomUpdate() {
    }

    public BookingRoomUpdate(Booking booking, Rooms roomsByNewRoomId, Rooms roomsByOldRoomId, Date dateUpdated) {
       this.booking = booking;
       this.roomsByNewRoomId = roomsByNewRoomId;
       this.roomsByOldRoomId = roomsByOldRoomId;
       this.dateUpdated = dateUpdated;
    }
   
    public Integer getBookingUpdateId() {
        return this.bookingUpdateId;
    }
    
    public void setBookingUpdateId(Integer bookingUpdateId) {
        this.bookingUpdateId = bookingUpdateId;
    }
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }
    public Rooms getRoomsByNewRoomId() {
        return this.roomsByNewRoomId;
    }
    
    public void setRoomsByNewRoomId(Rooms roomsByNewRoomId) {
        this.roomsByNewRoomId = roomsByNewRoomId;
    }
    public Rooms getRoomsByOldRoomId() {
        return this.roomsByOldRoomId;
    }
    
    public void setRoomsByOldRoomId(Rooms roomsByOldRoomId) {
        this.roomsByOldRoomId = roomsByOldRoomId;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


