package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1



/**
 * BookingDeleteHistory generated by hbm2java
 */
public class BookingDeleteHistory  implements java.io.Serializable {


     private Integer bookingDeleteCaseId;
     private Booking booking;
     private Rooms rooms;
     private Users users;

    public BookingDeleteHistory() {
    }

    public BookingDeleteHistory(Booking booking, Rooms rooms, Users users) {
       this.booking = booking;
       this.rooms = rooms;
       this.users = users;
    }
   
    public Integer getBookingDeleteCaseId() {
        return this.bookingDeleteCaseId;
    }
    
    public void setBookingDeleteCaseId(Integer bookingDeleteCaseId) {
        this.bookingDeleteCaseId = bookingDeleteCaseId;
    }
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


