package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BookingListInsert generated by hbm2java
 */
public class BookingListInsert  implements java.io.Serializable {


     private Integer bookingInsertId;
     private Rooms rooms;
     private Users users;
     private Date dateFrom;
     private Date dateTo;

    public BookingListInsert() {
    }

    public BookingListInsert(Rooms rooms, Users users, Date dateFrom, Date dateTo) {
       this.rooms = rooms;
       this.users = users;
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
    }
   
    public Integer getBookingInsertId() {
        return this.bookingInsertId;
    }
    
    public void setBookingInsertId(Integer bookingInsertId) {
        this.bookingInsertId = bookingInsertId;
    }
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }




}


