package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1



/**
 * HotelRating generated by hbm2java
 */
public class HotelRating  implements java.io.Serializable {


     private Integer ratingId;
     private Hotels hotels;
     private int rateValue;

    public HotelRating() {
    }

    public HotelRating(Hotels hotels, int rateValue) {
       this.hotels = hotels;
       this.rateValue = rateValue;
    }
   
    public Integer getRatingId() {
        return this.ratingId;
    }
    
    public void setRatingId(Integer ratingId) {
        this.ratingId = ratingId;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }
    public int getRateValue() {
        return this.rateValue;
    }
    
    public void setRateValue(int rateValue) {
        this.rateValue = rateValue;
    }




}


