package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1



/**
 * HotelRating generated by hbm2java
 */
public class HotelRating  implements java.io.Serializable {


     private Integer ratingId;
     private Hotels hotels;
     private double rateValue;
     private int numOfUsers;

    public HotelRating() {
    }

    public HotelRating(Hotels hotels, double rateValue, int numOfUsers) {
       this.hotels = hotels;
       this.rateValue = rateValue;
       this.numOfUsers = numOfUsers;
    }
   
    public Integer getRatingId() {
        return this.ratingId;
    }
    
    public void setRatingId(Integer ratingId) {
        this.ratingId = ratingId;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }
    public double getRateValue() {
        return this.rateValue;
    }
    
    public void setRateValue(double rateValue) {
        this.rateValue = rateValue;
    }
    public int getNumOfUsers() {
        return this.numOfUsers;
    }
    
    public void setNumOfUsers(int numOfUsers) {
        this.numOfUsers = numOfUsers;
    }




}


