package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotels generated by hbm2java
 */
public class Hotels  implements java.io.Serializable {


     private int hotelId;
     private Country country;
     private HotelChains hotelChains;
     private String hotelName;
     private String emailAddress;
     private String hotelAddress;
     private String hotelLongitude;
     private String hotelLatitude;
     private Integer hotelStars;
     private Double distanceFromGc;
     private Set specificHotelFeatures = new HashSet(0);
     private Set hotelRatings = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set roomses = new HashSet(0);
     private Set roomses_1 = new HashSet(0);
     private Set roomses_2 = new HashSet(0);
     private Set hotelPhotoses = new HashSet(0);

    public Hotels() {
    }

	
    public Hotels(int hotelId, Country country) {
        this.hotelId = hotelId;
        this.country = country;
    }
    public Hotels(int hotelId, Country country, HotelChains hotelChains, String hotelName, String emailAddress, String hotelAddress, String hotelLongitude, String hotelLatitude, Integer hotelStars, Double distanceFromGc, Set specificHotelFeatures, Set hotelRatings, Set commentses, Set roomses, Set roomses_1, Set roomses_2, Set hotelPhotoses) {
       this.hotelId = hotelId;
       this.country = country;
       this.hotelChains = hotelChains;
       this.hotelName = hotelName;
       this.emailAddress = emailAddress;
       this.hotelAddress = hotelAddress;
       this.hotelLongitude = hotelLongitude;
       this.hotelLatitude = hotelLatitude;
       this.hotelStars = hotelStars;
       this.distanceFromGc = distanceFromGc;
       this.specificHotelFeatures = specificHotelFeatures;
       this.hotelRatings = hotelRatings;
       this.commentses = commentses;
       this.roomses = roomses;
       this.roomses_1 = roomses_1;
       this.roomses_2 = roomses_2;
       this.hotelPhotoses = hotelPhotoses;
    }
   
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public HotelChains getHotelChains() {
        return this.hotelChains;
    }
    
    public void setHotelChains(HotelChains hotelChains) {
        this.hotelChains = hotelChains;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getHotelAddress() {
        return this.hotelAddress;
    }
    
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }
    public String getHotelLongitude() {
        return this.hotelLongitude;
    }
    
    public void setHotelLongitude(String hotelLongitude) {
        this.hotelLongitude = hotelLongitude;
    }
    public String getHotelLatitude() {
        return this.hotelLatitude;
    }
    
    public void setHotelLatitude(String hotelLatitude) {
        this.hotelLatitude = hotelLatitude;
    }
    public Integer getHotelStars() {
        return this.hotelStars;
    }
    
    public void setHotelStars(Integer hotelStars) {
        this.hotelStars = hotelStars;
    }
    public Double getDistanceFromGc() {
        return this.distanceFromGc;
    }
    
    public void setDistanceFromGc(Double distanceFromGc) {
        this.distanceFromGc = distanceFromGc;
    }
    public Set getSpecificHotelFeatures() {
        return this.specificHotelFeatures;
    }
    
    public void setSpecificHotelFeatures(Set specificHotelFeatures) {
        this.specificHotelFeatures = specificHotelFeatures;
    }
    public Set getHotelRatings() {
        return this.hotelRatings;
    }
    
    public void setHotelRatings(Set hotelRatings) {
        this.hotelRatings = hotelRatings;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getRoomses() {
        return this.roomses;
    }
    
    public void setRoomses(Set roomses) {
        this.roomses = roomses;
    }
    public Set getRoomses_1() {
        return this.roomses_1;
    }
    
    public void setRoomses_1(Set roomses_1) {
        this.roomses_1 = roomses_1;
    }
    public Set getRoomses_2() {
        return this.roomses_2;
    }
    
    public void setRoomses_2(Set roomses_2) {
        this.roomses_2 = roomses_2;
    }
    public Set getHotelPhotoses() {
        return this.hotelPhotoses;
    }
    
    public void setHotelPhotoses(Set hotelPhotoses) {
        this.hotelPhotoses = hotelPhotoses;
    }




}


