package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1



/**
 * HotelPhotos generated by hbm2java
 */
public class HotelPhotos  implements java.io.Serializable {


     private Integer photoId;
     private Hotels hotels;
     private String photoPath;

    public HotelPhotos() {
    }

    public HotelPhotos(Hotels hotels, String photoPath) {
       this.hotels = hotels;
       this.photoPath = photoPath;
    }
   
    public Integer getPhotoId() {
        return this.photoId;
    }
    
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }
    public String getPhotoPath() {
        return this.photoPath;
    }
    
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }




}


