package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HotelChains generated by hbm2java
 */
public class HotelChains  implements java.io.Serializable {


     private String hotelChainCode;
     private String hotelChainName;
     private Set hotelses = new HashSet(0);

    public HotelChains() {
    }

	
    public HotelChains(String hotelChainCode) {
        this.hotelChainCode = hotelChainCode;
    }
    public HotelChains(String hotelChainCode, String hotelChainName, Set hotelses) {
       this.hotelChainCode = hotelChainCode;
       this.hotelChainName = hotelChainName;
       this.hotelses = hotelses;
    }
   
    public String getHotelChainCode() {
        return this.hotelChainCode;
    }
    
    public void setHotelChainCode(String hotelChainCode) {
        this.hotelChainCode = hotelChainCode;
    }
    public String getHotelChainName() {
        return this.hotelChainName;
    }
    
    public void setHotelChainName(String hotelChainName) {
        this.hotelChainName = hotelChainName;
    }
    public Set getHotelses() {
        return this.hotelses;
    }
    
    public void setHotelses(Set hotelses) {
        this.hotelses = hotelses;
    }




}


