package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RoomTypes generated by hbm2java
 */
public class RoomTypes  implements java.io.Serializable {


     private String roomTypeCode;
     private BigDecimal standardRoomRate;
     private String roomTypeDescription;
     private Integer maxChildern;
     private Integer maxAdult;
     private Set roomses = new HashSet(0);
     private Set roomses_1 = new HashSet(0);
     private Set roomses_2 = new HashSet(0);

    public RoomTypes() {
    }

	
    public RoomTypes(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode;
    }
    public RoomTypes(String roomTypeCode, BigDecimal standardRoomRate, String roomTypeDescription, Integer maxChildern, Integer maxAdult, Set roomses, Set roomses_1, Set roomses_2) {
       this.roomTypeCode = roomTypeCode;
       this.standardRoomRate = standardRoomRate;
       this.roomTypeDescription = roomTypeDescription;
       this.maxChildern = maxChildern;
       this.maxAdult = maxAdult;
       this.roomses = roomses;
       this.roomses_1 = roomses_1;
       this.roomses_2 = roomses_2;
    }
   
    public String getRoomTypeCode() {
        return this.roomTypeCode;
    }
    
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode;
    }
    public BigDecimal getStandardRoomRate() {
        return this.standardRoomRate;
    }
    
    public void setStandardRoomRate(BigDecimal standardRoomRate) {
        this.standardRoomRate = standardRoomRate;
    }
    public String getRoomTypeDescription() {
        return this.roomTypeDescription;
    }
    
    public void setRoomTypeDescription(String roomTypeDescription) {
        this.roomTypeDescription = roomTypeDescription;
    }
    public Integer getMaxChildern() {
        return this.maxChildern;
    }
    
    public void setMaxChildern(Integer maxChildern) {
        this.maxChildern = maxChildern;
    }
    public Integer getMaxAdult() {
        return this.maxAdult;
    }
    
    public void setMaxAdult(Integer maxAdult) {
        this.maxAdult = maxAdult;
    }
    public Set getRoomses() {
        return this.roomses;
    }
    
    public void setRoomses(Set roomses) {
        this.roomses = roomses;
    }
    public Set getRoomses_1() {
        return this.roomses_1;
    }
    
    public void setRoomses_1(Set roomses_1) {
        this.roomses_1 = roomses_1;
    }
    public Set getRoomses_2() {
        return this.roomses_2;
    }
    
    public void setRoomses_2(Set roomses_2) {
        this.roomses_2 = roomses_2;
    }




}


