package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rooms generated by hbm2java
 */
public class Rooms  implements java.io.Serializable {


     private int roomId;
     private Hotels hotels;
     private RoomTypes roomTypes;
     private Integer roomFloor;
     private Integer roomNumber;
     private Set bookings = new HashSet(0);
     private Set bookingRoomUpdatesForNewRoomId = new HashSet(0);
     private Set roomAvailabilities = new HashSet(0);
     private Set bookingDeleteHistories = new HashSet(0);
     private Set bookingRoomUpdatesForOldRoomId = new HashSet(0);

    public Rooms() {
    }

	
    public Rooms(int roomId, RoomTypes roomTypes) {
        this.roomId = roomId;
        this.roomTypes = roomTypes;
    }
    public Rooms(int roomId, Hotels hotels, RoomTypes roomTypes, Integer roomFloor, Integer roomNumber, Set bookings, Set bookingRoomUpdatesForNewRoomId, Set roomAvailabilities, Set bookingDeleteHistories, Set bookingRoomUpdatesForOldRoomId) {
       this.roomId = roomId;
       this.hotels = hotels;
       this.roomTypes = roomTypes;
       this.roomFloor = roomFloor;
       this.roomNumber = roomNumber;
       this.bookings = bookings;
       this.bookingRoomUpdatesForNewRoomId = bookingRoomUpdatesForNewRoomId;
       this.roomAvailabilities = roomAvailabilities;
       this.bookingDeleteHistories = bookingDeleteHistories;
       this.bookingRoomUpdatesForOldRoomId = bookingRoomUpdatesForOldRoomId;
    }
   
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }
    public RoomTypes getRoomTypes() {
        return this.roomTypes;
    }
    
    public void setRoomTypes(RoomTypes roomTypes) {
        this.roomTypes = roomTypes;
    }
    public Integer getRoomFloor() {
        return this.roomFloor;
    }
    
    public void setRoomFloor(Integer roomFloor) {
        this.roomFloor = roomFloor;
    }
    public Integer getRoomNumber() {
        return this.roomNumber;
    }
    
    public void setRoomNumber(Integer roomNumber) {
        this.roomNumber = roomNumber;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }
    public Set getBookingRoomUpdatesForNewRoomId() {
        return this.bookingRoomUpdatesForNewRoomId;
    }
    
    public void setBookingRoomUpdatesForNewRoomId(Set bookingRoomUpdatesForNewRoomId) {
        this.bookingRoomUpdatesForNewRoomId = bookingRoomUpdatesForNewRoomId;
    }
    public Set getRoomAvailabilities() {
        return this.roomAvailabilities;
    }
    
    public void setRoomAvailabilities(Set roomAvailabilities) {
        this.roomAvailabilities = roomAvailabilities;
    }
    public Set getBookingDeleteHistories() {
        return this.bookingDeleteHistories;
    }
    
    public void setBookingDeleteHistories(Set bookingDeleteHistories) {
        this.bookingDeleteHistories = bookingDeleteHistories;
    }
    public Set getBookingRoomUpdatesForOldRoomId() {
        return this.bookingRoomUpdatesForOldRoomId;
    }
    
    public void setBookingRoomUpdatesForOldRoomId(Set bookingRoomUpdatesForOldRoomId) {
        this.bookingRoomUpdatesForOldRoomId = bookingRoomUpdatesForOldRoomId;
    }




}


