package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RoomAvailability generated by hbm2java
 */
public class RoomAvailability  implements java.io.Serializable {


     private Integer caseAvailId;
     private Rooms rooms;
     private String roomAvailabilityStatus;
     private Date dueDate;

    public RoomAvailability() {
    }

	
    public RoomAvailability(Rooms rooms, String roomAvailabilityStatus) {
        this.rooms = rooms;
        this.roomAvailabilityStatus = roomAvailabilityStatus;
    }
    public RoomAvailability(Rooms rooms, String roomAvailabilityStatus, Date dueDate) {
       this.rooms = rooms;
       this.roomAvailabilityStatus = roomAvailabilityStatus;
       this.dueDate = dueDate;
    }
   
    public Integer getCaseAvailId() {
        return this.caseAvailId;
    }
    
    public void setCaseAvailId(Integer caseAvailId) {
        this.caseAvailId = caseAvailId;
    }
    public Rooms getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Rooms rooms) {
        this.rooms = rooms;
    }
    public String getRoomAvailabilityStatus() {
        return this.roomAvailabilityStatus;
    }
    
    public void setRoomAvailabilityStatus(String roomAvailabilityStatus) {
        this.roomAvailabilityStatus = roomAvailabilityStatus;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }




}


