package Models;
// Generated Jan 15, 2021 6:32:47 AM by Hibernate Tools 4.3.1



/**
 * SpecificHotelFeature generated by hbm2java
 */
public class SpecificHotelFeature  implements java.io.Serializable {


     private Integer featureId;
     private HotelFeatures hotelFeatures;
     private Hotels hotels;

    public SpecificHotelFeature() {
    }

    public SpecificHotelFeature(HotelFeatures hotelFeatures, Hotels hotels) {
       this.hotelFeatures = hotelFeatures;
       this.hotels = hotels;
    }
   
    public Integer getFeatureId() {
        return this.featureId;
    }
    
    public void setFeatureId(Integer featureId) {
        this.featureId = featureId;
    }
    public HotelFeatures getHotelFeatures() {
        return this.hotelFeatures;
    }
    
    public void setHotelFeatures(HotelFeatures hotelFeatures) {
        this.hotelFeatures = hotelFeatures;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }




}


