package Models;
// Generated Jan 4, 2021 6:34:40 PM by Hibernate Tools 4.3.1



/**
 * SpecificHotelFeature generated by hbm2java
 */
public class SpecificHotelFeature  implements java.io.Serializable {


     private int featureId;
     private HotelFeatures hotelFeatures;
     private Hotels hotels;

    public SpecificHotelFeature() {
    }

    public SpecificHotelFeature(int featureId, HotelFeatures hotelFeatures, Hotels hotels) {
       this.featureId = featureId;
       this.hotelFeatures = hotelFeatures;
       this.hotels = hotels;
    }
   
    public int getFeatureId() {
        return this.featureId;
    }
    
    public void setFeatureId(int featureId) {
        this.featureId = featureId;
    }
    public HotelFeatures getHotelFeatures() {
        return this.hotelFeatures;
    }
    
    public void setHotelFeatures(HotelFeatures hotelFeatures) {
        this.hotelFeatures = hotelFeatures;
    }
    public Hotels getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Hotels hotels) {
        this.hotels = hotels;
    }




}


